# Form implementation generated from reading ui file 'importation.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(523, 327)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        MainWindow.setFont(font)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        self.labelArticles = QtWidgets.QLabel(self.centralwidget)
        self.labelArticles.setFont(font)
        self.labelArticles.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.labelArticles.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelArticles.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.labelArticles.setObjectName("labelArticles")
        self.gridLayout.addWidget(self.labelArticles, 4, 0, 1, 1)

        spacerItem = QtWidgets.QSpacerItem(44, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 5, 1, 1)

        self.BCAButton = QtWidgets.QPushButton(self.centralwidget)
        self.BCAButton.setFont(font)
        self.BCAButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.BCAButton.setObjectName("BCAButton")
        self.gridLayout.addWidget(self.BCAButton, 5, 4, 1, 1)

        self.labelBasePath = QtWidgets.QLabel(self.centralwidget)
        self.labelBasePath.setFont(font)
        self.labelBasePath.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.labelBasePath.setScaledContents(False)
        self.labelBasePath.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelBasePath.setWordWrap(False)
        self.labelBasePath.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.labelBasePath.setObjectName("labelBasePath")
        self.gridLayout.addWidget(self.labelBasePath, 0, 0, 1, 1)

        self.articlesButton = QtWidgets.QPushButton(self.centralwidget)
        self.articlesButton.setFont(font)
        self.articlesButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.articlesButton.setMouseTracking(False)
        self.articlesButton.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.articlesButton.setObjectName("articlesButton")
        self.gridLayout.addWidget(self.articlesButton, 5, 3, 1, 1)

        self.articlesInput = QtWidgets.QLineEdit(self.centralwidget)
        self.articlesInput.setObjectName("articlesInput")
        self.gridLayout.addWidget(self.articlesInput, 4, 2, 1, 2)

        self.baseInput = QtWidgets.QLineEdit(self.centralwidget)
        self.baseInput.setObjectName("baseInput")
        self.gridLayout.addWidget(self.baseInput, 0, 2, 1, 2)

        self.BCAInput = QtWidgets.QLineEdit(self.centralwidget)
        self.BCAInput.setObjectName("BCAInput")
        self.gridLayout.addWidget(self.BCAInput, 1, 4, 1, 2)

        self.labelProviderFiles = QtWidgets.QLabel(self.centralwidget)
        self.labelProviderFiles.setFont(font)
        self.labelProviderFiles.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelProviderFiles.setObjectName("labelProviderFiles")
        self.gridLayout.addWidget(self.labelProviderFiles, 1, 3, 1, 1)

        spacerItem1 = QtWidgets.QSpacerItem(52, 24, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Imports kwisatz"))
        self.labelArticles.setText(_translate("MainWindow", "Chemin du dossier\n"
"article"))
        self.BCAButton.setText(_translate("MainWindow", "Importation\n"
"BCA fournisseurs"))
        self.labelBasePath.setText(_translate("MainWindow", "Chemin du dossier\n"
" magasin"))
        self.articlesButton.setText(_translate("MainWindow", "Importation\n"
"Articles"))
        self.labelProviderFiles.setText(_translate("MainWindow", "Chemin des fichiers fournisseurs\n"
"à intégrer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    # b2.setIcon(QIcon(QPixmap("python.gif")))
    MainWindow.show()
    sys.exit(app.exec())
