# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaceClientFinale.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(597, 205)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        MainWindow.setFont(font)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 1, 1, 5)
        
        self.BCAButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(10)
        self.BCAButton.setFont(font)
        self.BCAButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BCAButton.setObjectName("BCAButton")
        self.gridLayout.addWidget(self.BCAButton, 6, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(44, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 6, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(52, 24, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 2)
        self.articlesButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(10)
        self.articlesButton.setFont(font)
        self.articlesButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.articlesButton.setMouseTracking(False)
        self.articlesButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.articlesButton.setObjectName("articlesButton")
        self.gridLayout.addWidget(self.articlesButton, 6, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 4)
        self.exportButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.exportButton.setFont(font)
        self.exportButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exportButton.setObjectName("exportButton")
        self.gridLayout.addWidget(self.exportButton, 6, 2, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Imports kwisatz"))
        self.BCAButton.setText(_translate("MainWindow", "Importation\n"
"BCA fournisseurs"))
        self.articlesButton.setText(_translate("MainWindow", "Importation\n"
"Articles"))
        self.label.setText(_translate("MainWindow", "Cette interface vous permet d\'importer vers Kwisatz : les articles envoyés par la centrale ainsi que\n"
"vos bons de commandes fournisseurs."))
        self.exportButton.setText(_translate("MainWindow", "Exportation des bons\n"
"de commandes fournisseurs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication.instance() 
    if not app: # sinon on crée une instance de QApplication
        app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.setWindowIcon(QtGui.QIcon("b2m.ico"))
    MainWindow.show()
    sys.exit(app.exec())